language: cpp
dist: trusty
compiler: gcc

before_install:
   - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
   - sudo add-apt-repository -y ppa:beineri/opt-qt591-trusty
   - sudo apt-get update -qq
   
install:
   - sudo apt-get install -qq gcc-7 g++-7
   - sudo apt-get install -qq cmake
   - sudo apt-get install -qq ggcov
   - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-7 90
   - sudo apt-get install -qq lcov
   - gem install coveralls-lcov
   - sudo apt-get install -qq qt59base
   - sudo apt-get install -qq libgles2-mesa-dev libqt5gui5 libqt5serialport5-dev libqt5printsupport5 libqt5widgets5 libgles2-mesa libgl1-mesa-dev libgl1-mesa-glx libglapi-mesa libegl1-mesa-dev libpango-1.0-0
   - sudo apt-get install -qq zlib1g-dev libudev-dev
   - sudo apt-get install -qq libboost-all-dev
   
before_script:
   - "export DISPLAY=:99.0"
   - "sh -e /etc/init.d/xvfb start"
   - sleep 3 # Give xvfb some time to start

script:
   - source /opt/qt59/bin/qt59-env.sh

   # Get and build required libs/apps. TODO: change to conan.io packages
   - ./build_scripts/build_gtest.sh

   # Build application
   - ./build_scripts/build_app.sh --path $(pwd) --build --test --coverage
